require('lazy').setup({
  require('plugins.lsp'),
  require('plugins.treesitter'),
  require('plugins.ui'),
  require('plugins.git'),
  require('plugins.editor'),
  require('plugins.testing'),
  require('plugins.ai'),
})
